version: '3'
services:
  link-downloader:
    build: .
    ports:
      - '8000:8000'
    container_name: 'link_downloader'
    environment:
      - PYTHONIOENCODING=UTF-8
    working_dir: '/apps/link_downloader'
    depends_on:
      - 'postgres'
    restart: unless-stopped
    env_file:
      .env
  postgres:
    image: postgres:12
    restart: unless-stopped
    env_file:
      .env
